/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

/*
class Coche{
    var marca: String = "Ford"
    var modelo: Int = 2020
}
*/
class Coche (private var _marca: String = "Ford", private var _modelo: Int = 2020 ){
    var marca: String
    get() = _marca
    set(value){
        marca = value
    }

    var modelo: Int
    get() = _modelo
    set(value){
        modelo = value
    }
}


// El bloque 'init' se ejecuta cuando se crea una instancia de la clase (un objeto).
// Los 'métodos' son funciones que pertenecen a la clase y definen su comportamiento.
class Rectangulo(val ancho: Double, val alto: Double) {
    var area: Double

    // El bloque init se usa para inicializar propiedades o ejecutar código en la creación.
    init {
        // 'area' se calcula una vez cuando se crea el objeto.
        area = ancho * alto
        println("Se ha creado un rectángulo de $ancho x $alto con un área de $area")
    }

    // Un método de la clase
    fun describir() {
        println("Este es un rectángulo.")
    }

    // Un método que realiza un cálculo
    fun calcularPerimetro(): Double {
        return 2 * (ancho + alto)
    }
}


fun main() {

    val coche = Coche("Fiat", 2015)
    println("Marca: ${coche.marca}")
    println("Modelo: ${coche.modelo}")

    val rectangulo = Rectangulo(10.0, 5.0)
    println("Area ${rectangulo.area}")
    println("Perimetro ${rectangulo.calcularPerimetro()}")
    rectangulo.describir()
}