/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

/*
class Coche{
    var marca: String = "Ford"
    var modelo: Int = 2020
}
*/
class Coche (private var _marca: String = "Ford", private var _modelo: Int = 2020 ){
    var marca: String
    get() = _marca
    set(value){
        _marca = value
    }

    var modelo: Int
    get() = _modelo
    set(value){
        _modelo = value
    }
}

interface Perimetrable{
    fun calcularPerimetro(): Double
    fun describir()
}

class Circulo(val radio: Int): Perimetrable{
    var area: Double

    init{
        area = Math.PI*radio*radio
        println("Se ha creado un circulo de radio $radio con un área de $area")
    }

    override fun describir() {
        println("Este es un circulo.")
    }

    override fun calcularPerimetro(): Double {
        return 2 * Math.PI * radio
    }
}


// El bloque 'init' se ejecuta cuando se crea una instancia de la clase (un objeto).
// Los 'métodos' son funciones que pertenecen a la clase y definen su comportamiento.
class Rectangulo(val ancho: Double, val alto: Double): Perimetrable {
    var area: Double

    // El bloque init se usa para inicializar propiedades o ejecutar código en la creación.
    init {
        // 'area' se calcula una vez cuando se crea el objeto.
        area = ancho * alto
        println("Se ha creado un rectángulo de $ancho x $alto con un área de $area")
    }

    // Un método de la clase
    override fun describir() {
        println("Este es un rectángulo.")
    }

    // Un método que realiza un cálculo
    override fun calcularPerimetro(): Double {
        return 2 * (ancho + alto)
    }
}


fun main() {

    val coche = Coche("Fiat", 2015)
    println("Marca: ${coche.marca}")
    println("Modelo: ${coche.modelo}")

    val rectangulo = Rectangulo(10.0, 5.0)
    val circulo = Circulo(5)
    val figuras: List<Perimetrable> = listOf(rectangulo, circulo)

    for(figura in figuras){
        figura.describir()
        println("Perimetro: ${figura.calcularPerimetro()}")
    }

}